### ISSUE TITLE
Removing last node using jstree-actions causes exception

### ISSUE THREAD

**Issue by slbug** [alexandernst/jstree-actions#4] opened 2015-10-27 10:31 UTC
Here is example. http://jsfiddle.net/1m97d73f/1/

If you remove node using external button everything will be ok. If using jstree-actions button you will receive exception

**Comment by slbug** [comment] 2015-10-27 10:32
May be it's because we removing focused node. /cc @vakata

**Comment by alexandernst** [comment] 2015-10-27 10:57
I updated your jsfiddle with the unminified version of my plugin for easier debugging: http://jsfiddle.net/1m97d73f/2/

This looks very weird. Both `delete_node` calls are receiving exactly the same object (check the `console.log`s that I placed before each call), but for some reason the call from inside the callback is failing.

**Comment by alexandernst** [comment] 2015-10-27 23:14
I'm closing this as this is clearly not a bug in my plugin: http://jsfiddle.net/1m97d73f/3/

I opened an issue for you: https://github.com/vakata/jstree/issues/1265

**Closed as completed by alexandernst** 2015-10-27 23:14 UTC
